### ISSUE TITLE
Re-enable node-gyp integration workflow

### ISSUE THREAD

**Issue by targos** [nodejs/gyp-next#150]
Blocked on https://github.com/nodejs/node-gyp/issues/2645

It's permanently red, so I disabled it in https://github.com/nodejs/gyp-next/actions/workflows/node-gyp.yml

**Comment by gengjiawen** [comment]
Thanks to @rvagg , the fix is on https://github.com/nodejs/node-gyp/pull/2662

**Comment by gengjiawen** [comment]
fixed in upstream. I re-enbaled.
