### ISSUE TITLE
Figure out licensing

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/gyp-next#2]
The project is currently licensed to Google Inc. using a BSD 3-Clause license. Ideally, we should be using MIT instead? Or atleast relicense it to new contributors? Anyway, we could also do this one file at a time. Or use a dual-license. Let's use this thread to brainstorm this.

**Comment by targos** [comment]
Can this be closed after https://github.com/nodejs/gyp-next/commit/fd2032298c8e9946e37ee43633e0218e2207cef6 ?
I don't think we are allowed to change the licence to MIT (and BSD is fine imo)

**Comment by ryzokuken** [comment]
Yes, this can be closed now I think. Thanks.
