### ISSUE TITLE
At some point, we should stop telling contributors to update `setuptools`

### ISSUE THREAD

**Issue by Jayman2000** [nodejs/gyp-next#277]
[`docs/Hacking.md` says:](https://github.com/nodejs/gyp-next/blob/a61df708e3c2249f54b32e355598b11e35e7612e/docs/Hacking.md#testing-your-change)

> GYP has a suite of tests which you can run with the provided test driver
> to make sure your changes aren't breaking anything important.
>
> You run the test driver with e.g.
>
> ``` sh
> $ python -m pip install --upgrade pip setuptools
> […]
> ```

[As of Python 3.12, Python no longer comes with the `setuptools` package by default.](https://docs.python.org/3/whatsnew/3.12.html#ensurepip) I tried following the instructions in `docs/Hacking.md` in a fresh Python 3.13 virtual environment, but I skipped installing/upgrading `setuptools` (I only upgraded `pip`). Everything worked fine.

At some point, `docs/Hacking.md` so that it doesn’t tell users to upgrade `setuptools`. We could do it after Python 3.10 has reached end of life, or we could do it sooner with a note that says “hey, if you’re using Python 3.12+, don’t upgrade `setuptools`”.

**Comment by cclauss** [comment]
I see no downside to encouraging users to upgrade `setuptools` because that is the way to get `packaging` in modern Python.

https://github.com/search?q=repo%3Anodejs%2Fgyp-next%20packaging&type=code

**Comment by Jayman2000** [comment]
> I see no downside to encouraging users to upgrade `setuptools` because that is the way to get `packaging` in modern Python.
> 
> https://github.com/search?q=repo%3Anodejs%2Fgyp-next%20packaging&type=code

Let’s say that I create and activate a fresh virtual environment using Python 3.13. When I run the command `python -m pip install --upgrade pip setuptools`, it will install the `setuptools` package because the `setuptools` package wasn’t already installed. Is installing the `setuptools` package manually the right thing to do in this scenario? Will I not have access to `packaging` if I don’t manually install `setuptools`? I had assumed that pip would get all of the build dependencies for me when I ran `pip install --editable ".[dev]"`, but I’m not an expert in Python packaging.

**Comment by cclauss** [comment]
You are correct.

Installing `gyp-next` via `pyproject.toml` forces the installation of a sufficiently modern `setuptools` as demonstrated in:
* #278
