### ISSUE TITLE
Fold long lines in Python code to max-line-length=88

### ISSUE THREAD

**Issue by cclauss** [nodejs/gyp-next#56]
As discussed in #54, `flake8 --max-line-length=88` currently find 60+ lines in Python files that are longer than 88 characters.  psf/black will not auto-fix most of these issues so it is a manual job to wrap these lines at 88 chars max without breaking any functionality or tests.

**Comment by iandrc** [comment]
@cclauss I would like to try this one

**Comment by ryzokuken** [comment]
@iandrc please go ahead!

**Comment by iandrc** [comment]
@ryzokuken @targos I need a bit of your help :)

See https://github.com/nodejs/gyp-next/pull/57

**Comment by iandrc** [comment]
@ryzokuken @targos Guys, I believe you can close this one.

**Comment by ryzokuken** [comment]
Oops, yes.

**Comment by cclauss** [comment]
> you can close this one.

Here is a poweruser tip.  When you create a PR that closes an issue, instead of putting `Refs: #56`, put `closes #56` or `fixes #56` or `resolves #56` because GitHub will autoclose the issue when the PR lands.

Thanks for your contribution!
