### ISSUE TITLE
arm on windows issue

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/gyp-next#64]
OK, so I think I've found a way of doing this without patching gyp-next (apologies I can't push a commit because I don't own this PR), but this seems to compile OK:

```diff --git a/tools/v8_gypfiles/v8.gyp b/tools/v8_gypfiles/v8.gyp
index aebb528..f75147f 100644
--- a/tools/v8_gypfiles/v8.gyp
+++ b/tools/v8_gypfiles/v8.gyp
@@ -796,6 +796,13 @@
               ],
             }],
             ['OS=="win"', {
+              'conditions': [
+                ['v8_target_arch=="arm64"', {
+                  # Windows on Arm requires explicitly enabling the Microsoft
+                  # Arm Assembler (marmasm) for this component.
+                  'msvs_enable_marmasm': 1
+                }]
+              ]
               'sources': [
                 '<!@pymod_do_main(GN-scraper "<(V8_ROOT)/BUILD.gn"  "\\"v8_base_without_compiler.*?is_win.*?sources \+= ")',
               ],
```

_Originally posted by @richard-townsend-arm in https://github.com/nodejs/node/pull/34337#issuecomment-690360516_

**Comment by gengjiawen** [comment]
@targos will it make sense if the cpu is arm or arm64 we add this attribute by default ?

**Comment by targos** [comment]
Seems good to me, but I have no experience with ARM on Windows

**Comment by gengjiawen** [comment]
> Seems good to me, but I have no experience with ARM on Windows

I only deal with only once, but the building toolchain is cmake :)

**Comment by gengjiawen** [comment]
Another way is put the patch in `v8.gyp`. Either way is LGTM.

**Comment by gengjiawen** [comment]
Any thought put it on `v8.gyp` for now and move v8 8.5 merge to master forward ?

**Comment by targos** [comment]
We can do it as a last resort but the update to V8 8.5 is blocked on other issues anyway for now.

**Comment by gengjiawen** [comment]
> We can do it as a last resort but the update to V8 8.5 is blocked on other issues anyway for now.

You mean cross-compile on linux and smartOS ? https://ci.nodejs.org/job/node-cross-compile/30503/ 

![image](https://user-images.githubusercontent.com/3759816/93051042-6fd55280-f696-11ea-8545-a7c5810b33fd.png)

**Comment by targos** [comment]
> You mean cross-compile on linux and smartOS

Yes
