### ISSUE TITLE
auto release process for python package

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/gyp-next#97]
I think release-please can do this.

cc @ryzokuken @targos @cclauss

**Comment by cclauss** [comment]
Is this already done?
https://github.com/nodejs/gyp-next/blob/main/.github/workflows/release-please.yml

**Comment by gengjiawen** [comment]
Nope. There is no step publish to Pypi.

**Comment by gengjiawen** [comment]
duplicate of https://github.com/nodejs/gyp-next/issues/29.
